import { mkdir, writeFile } from 'node:fs/promises'
import path from 'node:path'

import { build } from 'esbuild'

const projectRoot = process.cwd()
const entryPoint = path.join(projectRoot, 'src/ui/portal-app.js')
const outputModule = path.join(projectRoot, 'src/generated/portal-app.generated.ts')

const result = await build({
  entryPoints: [entryPoint],
  bundle: true,
  format: 'iife',
  platform: 'browser',
  target: ['es2020'],
  write: false,
  charset: 'utf8',
  sourcemap: false,
  minify: false,
})

const bundle = result.outputFiles[0]?.text ?? ''
const html = `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Portal Explorer</title>
  </head>
  <body>
    <div id="app"></div>
    <script>${bundle}</script>
  </body>
</html>`

await mkdir(path.dirname(outputModule), { recursive: true })
await writeFile(
  outputModule,
  `// This file is auto-generated by scripts/build-app-ui.mjs.\nexport const PORTAL_APP_HTML = ${JSON.stringify(html)} as const\n`,
  'utf8',
)

console.log(`Built Portal app bundle -> ${path.relative(projectRoot, outputModule)}`)
